/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 magnifyingGlass.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magnifyingGlass.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.763, 29.246, 0]} rotation={[-1.68, -0.132, -0.761]} scale={7.087}>
        <mesh geometry={nodes.Torus_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Torus_2.geometry} material={materials.base} />
        <mesh geometry={nodes.Torus_3.geometry} material={materials.wood} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} position={[0, -4.209, 0]} scale={0.028} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.Material} position={[0, 0.415, 0]} scale={0.406} />
    </group>
  )
}

useGLTF.preload('/magnifyingGlass.gltf')
